spring.application.name=Questconnect
# Server Configuration
# Définit le port sur lequel votre API questconnect va s'exécuter
server.port=8080
# Définit le chemin de contexte pour l'application, toutes les requêtes seront préfixées par /questconnect.
server.servlet.context-path=/questconnect

# Toolkit API Configuration
# Définit l'URL de base pour l'API Toolkit
toolkit.api.base.url=http://localhost:8081/witcher-toolkit

# Logging Configuration
logging.level.root=INFO
logging.level.fr.meya.witcher=DEBUG

# Spring Boot Actuator Configuration (optionnel)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always